services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    restart: on-failure
    depends_on:
      - wordpress
    volumes:
      - /home/rguerrer/data/wordpress:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception

  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    restart: on-failure
    depends_on:
      - mariadb
    volumes:
      - /home/rguerrer/data/wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    restart: on-failure
    volumes:
      - /home/rguerrer/data/mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env

networks:
  inception:
    driver: bridge