
services:
  nginx:
    build:
      context: requirements/nginx/.
      args:
        CRED_PATH: ${CRED_PATH}
        SSL_CERT: ${SSL_CERT}
        SSL_KEY: ${SSL_KEY}
    container_name: nginx
    restart: on-failure
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html
    networks:
      inception:
    env_file:
      - .env
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    restart: on-failure
    depends_on:
      - mariadb
    volumes:
      - ./web:/var/www/html
    networks:
      inception:
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    restart: on-failure
    volumes:
      - ./database:/var/lib/mysql
    networks:
      inception:
    env_file:
      - .env

networks:
  inception:
    driver: bridge