
services:
  nginx:
    build:
      context: requirements/nginx/.
      args:
        CRED_PATH: ${CRED_PATH}
        SSL_CERT: ${SSL_CERT}
        SSL_KEY: ${SSL_KEY}
    container_name: nginx
    restart: on-failure
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "443:443"
    env_file:
      - .env

  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    restart: on-failure
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      inception:

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    restart: on-failure
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      inception:
    env_file:
      - .env

volumes:
  wordpress_data:
  mariadb_data:

networks:
  inception:
    driver: bridge